name: frontend

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .

command:
  bootstrap:
    environment:
      sdk: ^3.6.0
      flutter: ">=1.17.0"

    dependencies:
      animations: ^2.0.11
      auto_route: ^9.3.0+1
      dart_jsonwebtoken: ^2.14.0
      dio: ^5.7.0
      envied: ^1.0.0
      flutter:
        sdk: flutter
      flutter_bloc: ^9.0.0
      flutter_form_builder: ^9.7.0
      flutter_keyboard_visibility: ^6.0.0
      flutter_localizations:
        sdk: flutter
      flutter_secure_storage: ^9.2.4
      flutter_svg: ^2.0.10+1
      gap: ^3.0.1
      get_it: ^8.0.3
      google_fonts: ^6.2.1
      hydrated_bloc: ^10.0.0
      injectable: ^2.5.0
      intl: any
      json_annotation: ^4.9.0
      loader_overlay: ^5.0.0
      logger: ^2.4.0
      path: ^1.9.0
      path_provider: ^2.1.5
      pretty_dio_logger: ^1.4.0
      retrofit: ^4.4.1
      uuid: ^4.5.1

    dev_dependencies:
      analyzer: ^6.11.0
      auto_route_generator: ^9.3.1
      bloc_test: ^10.0.0
      build_runner: ^2.4.14
      envied_generator: ^1.0.0
      flutter_lints: ^5.0.0
      flutter_test:
        sdk: flutter
      injectable_generator: ^2.6.2
      json_serializable: ^6.7.1
      mocktail: ^1.0.4
      retrofit_generator: ^9.1.2
