name: network
description: "Network package containing network utilities"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  # Internal packages
  common:
    path: ../common
  data:
    path: ../data
  # End of Internal packages
  dio: ^5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.2

targets:
  $default:
    builders:
      json_serializable:
        options:
          generic_argument_factories: true