name: blocs
description: "Blocs package containing bloc utilities"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  # Internal Packages
  domain:
    path: ../domain
  models:
    path: ../models
  network:
    path: ../network
  # End of Internal Packages

  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.4