name: models
description: "Models package containing data models"
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: any
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.2

targets:
  $default:
    builders:
      json_serializable:
        options:
          generic_argument_factories: true
      freezed:
        options:
          generic_argument_factories: true
