name: routing
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  # Internal Packages
  blocs:
    path: ../blocs
  common:
    path: ../common
  design:
    path: ../design
  domain:
    path: ../domain
  models:
    path: ../models
  network:
    path: ../network
  products:
    path: ../../features/products
  # End of Internal Packages

  auto_route: ^9.3.0+1
  flutter:
    sdk: flutter
  loader_overlay: ^5.0.0

dev_dependencies:
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true