name: common
description: "Common package for the core"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  envied: ^1.0.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: any

dev_dependencies:
  build_runner: ^2.4.14
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter